model_params:
  name: "LineIdentificationModel"
  in_channels: 3
  latent_dim: 64
  point_loss_fn: "huber"
  loss_fn: "BCE"
  radius: 1.0
  num_points: 2
  img_size: 64
  reparameterize: False
  seg_loss_weight: 1
  raster_loss_weight: 0
  vector_loss_weight: 100
  seg_loss: "dice"
  path_encoder: "none"
  image_encoder: "simple"
#  image_encoder_weights: "logs/VanillaVAE/version_306/checkpoints/epoch=397-step=79599.ckpt"
  encode_image_canvas_separately: True
  perceptual_loss: "none"
  pad_image: False

exp_params:
  dataset: generated
  data_path: "./data/fixed/"
  img_size: 64
  batch_size: 64 # Better to have a square number
  val_batch_size: 16 # Better to have a square number
  val_shuffle: False
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  grow: True
  train_shuffle: False
  min_paths: 3
  max_paths: 8
  use_scheduler: False
  show_control_points: False
  shapes: 8
  points: 2
  num_images: 50
  num_val_images: 4
  force_grayscale: False
  radius: 1.0
  canvas_noise: False
  canvas_blur: False

trainer_params:
  gpus: [0]
  max_epochs: 25000

logging_params:
  save_dir: "logs/"
  name: "LineIdentificationModel"
  version: 103
  manual_seed: 1234
