model_params:
  name: "MarkedReconstructionModel"
  in_channels: 3
  latent_dim: 64
  point_loss_fn: "MSE"
  loss_fn: "BCE"
  radius: 0.512
  num_points: 4
  img_size: 512
  reparameterize: False
  seg_loss_weight: 1
  raster_loss_weight: 1
  vector_loss_weight: 100
  seg_loss: "dice"
  path_encoder: "none"
  image_encoder: "simple"
  perceptual_loss: "none"
  pad_image: False


exp_params:
  dataset: generated
  img_size: 512
  batch_size: 16 # Better to have a square number
  val_batch_size: 2 # Better to have a square number
  val_shuffle: False
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  grow: True
  train_shuffle: False
  min_paths: 3
  max_paths: 8
  use_scheduler: False
  show_control_points: False
  shapes: 8
  points: 4
  num_images: 50
  num_val_images: 4
  force_grayscale: False
  radius: 0.512
  canvas_noise: False
  canvas_blur: False

trainer_params:
  gpus: [0]
  max_epochs: 25000

logging_params:
  save_dir: "logs/"
  name: "MarkedReconstructionModel"
  version: 138
  manual_seed: 1234
