model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 2048
  img_size: 64
  loss_fn: "BCE"
  seg_loss_fn: "dice"
  seg_loss_weight: 1
  image_encoder: "simple"

exp_params:
  dataset: generated
  data_path: "./data/fixed/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  val_batch_size: 16 # Better to have a square number
  val_shuffle: False
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  grow: True
  train_shuffle: False
  min_paths: 3
  max_paths: 8
  use_scheduler: False
  show_control_points: False
  shapes: 8
  points: 2
  num_images: 200
  num_val_images: 4
  force_grayscale: False
  radius: 1.0
  canvas_noise: False
  indiv_raster_remaining_only: False

trainer_params:
  gpus: [0]
  max_epochs: 30000

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  version: 308
  manual_seed: 1234